version: '3.8'

services:
  # 1. AI Engine (Phân tích dữ liệu Đa phương thức)
  ai_engine:
    build: 
      context: ./ai_engine
      dockerfile: Dockerfile
    container_name: ai_engine_service
    ports:
      - "8000:8000"
    environment:
      - NODE_WEBHOOK_PROGRESS=http://web_backend:5000/api/webhook/update-progress
      - NODE_WEBHOOK_FINISHED=http://web_backend:5000/api/webhook/finished
    volumes:
      - ./ai_engine:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # 2. Web Backend (Node.js Express)
  web_backend:
    build: 
      context: ./web_platform/backend
      dockerfile: Dockerfile
    container_name: web_backend_service
    ports:
      - "5000:5000"
    env_file:
      - ./web_platform/backend/.env
    environment:
      - PYTHON_API_URL=http://ai_engine:8000
    depends_on:
      - ai_engine
    volumes:
      - ./web_platform/backend:/app
      - /app/node_modules

  # 3. Web Frontend (Next.js)
  frontend:
    build: 
      context: ./web_platform/frontend
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:5000
    depends_on:
      - web_backend
    stdin_open: true
    tty: true