"""
LazadaScraper — Network Interception by Playwright, uses pagination only.

Mechanism:
  1. Register listener page.on("response") to catch ALL review API responses
  2. Navigate + scroll -> page 1 is automatically intercepted
  3. Click "Next >" button repeatedly until out of pages or max_reviews reached

Why not replay POST manually:
  - Lazada API requires dynamic security tokens (_m_h5_tk, sign, t)
    generated by browser JS — cannot be generated externally.
  - Let browser click -> browser generates token -> we just intercept response.

URL pattern:
  https://www.lazada.vn/products/{slug}-i{itemId}-s{skuId}.html

Intercepted API endpoint:
  POST https://acs-m.lazada.vn/h5/mtop.lazada.review.item.getpcreviewlist/1.0/
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import logging
import re
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlparse

from scraper.exporter import ReviewExporter
from scraper.models import Review

log = logging.getLogger("LazadaScraper")

_THIS_DIR = Path(__file__).resolve().parent.parent.parent
SESSION_DIR = _THIS_DIR / "output" / "agent_sessions"
PAGE_SIZE = 10  # fallback; actual size detected from first response

# Poll chunk wait time (seconds)
CAPTCHA_POLL_CHUNK = 10.0
# Max time to automatically wait for CAPTCHA to be solved (5 minutes)
CAPTCHA_AUTO_WAIT = 300.0

_REVIEW_PATH = "mtop.lazada.review.item.getpcreviewlist"

# Selectors for "Next page" button - Lazada uses iweb-pagination-* (not ant-)
_NEXT_PAGE_SELECTORS = [
    "li.iweb-pagination-next:not(.iweb-pagination-disabled) button",
    "li.iweb-pagination-next:not(.iweb-pagination-disabled)",
    "button.iweb-pagination-item-link[aria-label='next page']:not([disabled])",
    "button.iweb-pagination-item-link[aria-label*='next' i]:not([disabled])",
]

# Selectors to scroll to the review / pagination section
_REVIEW_SECTION_SELECTORS = [
    ".mod-reviews-pagination",
    ".iweb-pagination",
    ".pdp-mod-review-pagination-info",
    "[data-spm='pdp_reviews']",
    "#module_review",
    ".mod-reviews",
    "[class*='pdp-review']",
]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _parse_ids(url: str) -> tuple[str, str]:
    """
    Returns (item_id, sku_id) from Lazada product URL.
    Pattern: /products/{slug}-i{itemId}-s{skuId}.html
    """
    path = urlparse(url).path
    m = re.search(r"-i(\d+)-s(\d+)", path)
    if m:
        return m.group(1), m.group(2)
    m = re.search(r"[/-]i(\d+)", path)
    if m:
        return m.group(1), ""
    raise ValueError(f"Could not find itemId in URL: {url}")


def _normalize_image_url(url: str) -> str:
    if url.startswith("//"):
        return "https:" + url
    return url


def _parse_date(ts) -> str:
    try:
        if isinstance(ts, str) and len(ts) >= 10 and ts[0].isdigit():
            return ts[:10]
        if isinstance(ts, str) and any(
            kw in ts for kw in ("tuần", "ngày", "tháng", "giờ", "phút")
        ):
            return ts
        if str(ts).lstrip("-").isdigit():
            ts_int = int(ts)
            if ts_int > 1e12:
                ts_int //= 1000
            dt = datetime.fromtimestamp(ts_int, tz=timezone.utc)
            return dt.strftime("%Y-%m-%d")
    except Exception:
        pass
    return str(ts) if ts else ""


def _extract_reviews_from_payload(data: dict) -> tuple[list[dict], int]:
    """Extract (items, total) from JSON payload of Lazada review API."""
    data2 = data.get("data") or {}
    module = data2.get("module") or {}
    items: list[dict] = module.get("reviews") or module.get("items") or []
    paging = data2.get("paging") or {}
    total = int(
        paging.get("totalItems")
        or module.get("totalCount")
        or module.get("totalitem")
        or 0
    )
    return items, total


def _normalize_review(raw: dict, product_url: str, product_name: str) -> Review | None:
    """Normalize review from raw dict -> Review model."""
    try:
        images: list[str] = []
        for media in raw.get("mediaList") or raw.get("images") or []:
            if isinstance(media, dict):
                url = (
                    media.get("coverUrl")
                    or media.get("url")
                    or media.get("videoUrl")
                    or ""
                )
            else:
                url = str(media)
            if url and not str(url).endswith(".mp4"):
                images.append(_normalize_image_url(url))

        ts = (
            raw.get("reviewTime")
            or raw.get("gmtCreateTime")
            or raw.get("createdTime")
            or ""
        )
        date_str = _parse_date(ts)

        text = ""
        content_list = raw.get("reviewContentList") or []
        if content_list and isinstance(content_list, list):
            text = content_list[0].get("content") or ""
        if not text:
            text = raw.get("reviewContent") or raw.get("content") or ""

        # Replace \n, \r with space to avoid creating extra rows in CSV
        clean_text = " ".join(str(text).split())

        return Review(
            product_name=product_name,
            text=clean_text,
            rating=int(raw.get("rating") or raw.get("score") or 0),
            date=date_str,
            image_urls=images,
            product_url=product_url,
            scraped_at=datetime.now().isoformat(),
        )
    except Exception as exc:
        log.debug("[Lazada] Skip malformed review: %s", exc)
        return None


# ---------------------------------------------------------------------------
# Main scraper class
# ---------------------------------------------------------------------------


class LazadaScraper:
    """
    Lazada scraper using Playwright network interception + UI pagination.
    Interface: async run(url, output_path, fmt, max_reviews) -> int.
    """

    SITE_NAME = "Lazada"

    def __init__(
        self,
        headless: bool = False,
        max_pages: int = 200,
        delay: float = 0.3,
    ):
        self.headless = headless
        self.max_pages = max_pages
        self.delay = delay
        SESSION_DIR.mkdir(parents=True, exist_ok=True)
        self._state_file = SESSION_DIR / "state_lazada.vn.json"
        self._seen: set[str] = set()
        self._t0: float = 0  # start time for speed calc

    # ------------------------------------------------------------------
    # Public entry point
    # ------------------------------------------------------------------

    async def run(
        self,
        url: str,
        output_path: str,
        fmt: str = "csv",
        max_reviews: int = 3000,
        progress_callback = None
    ) -> int:
        """Scrape Lazada reviews and write to file. Return the number of saved reviews."""
        import time
        print(f"  [{self.SITE_NAME}] CloakBrowser pagination scraper (optimized)")
        print(f"  headless={self.headless} | max_reviews={max_reviews:,} | delay={self.delay}s")

        try:
            item_id, sku_id = _parse_ids(url)
        except ValueError as exc:
            raise ValueError(str(exc)) from exc

        print(f"  itemId={item_id} | skuId={sku_id}")

        exporter = ReviewExporter(output_path, fmt)
        raw_reviews, product_name = await self._scrape_async(url, max_reviews, progress_callback)

        # Normalize + export (no need to dedup again because it was handled at raw level)
        batch: list[Review] = []
        for raw in raw_reviews:
            review = _normalize_review(raw, url, product_name)
            if review is not None:
                batch.append(review)

        total_saved = exporter.save_batch(batch) if batch else 0
        print(f"  [{self.SITE_NAME}] Total saved: {total_saved:,} reviews")
        return total_saved

    # ------------------------------------------------------------------
    # Core scraping (CloakBrowser + retry)
    # ------------------------------------------------------------------

    async def _scrape_async(
        self, product_url: str, max_reviews: int, progress_callback=None
    ) -> tuple[list[dict], str]:
        """Retry up to 3 times with exponential backoff."""
        for attempt in range(3):
            try:
                result = await self._scrape_attempt(product_url, max_reviews, progress_callback)
                if result[0]:
                    return result
                if attempt < 2:
                    wait = 2 ** attempt
                    log.warning("[Lazada] Attempt %d empty, retry in %ds", attempt + 1, wait)
                    await asyncio.sleep(wait)
            except Exception as exc:
                if attempt == 2:
                    log.error("[Lazada] All 3 attempts failed: %s", exc)
                    return [], ""
                wait = 2 ** attempt
                log.warning("[Lazada] Attempt %d error: %s - retry in %ds", attempt + 1, exc, wait)
                await asyncio.sleep(wait)
        return [], ""

    async def _scrape_attempt(
        self, product_url: str, max_reviews: int, progress_callback=None
    ) -> tuple[list[dict], str]:
        """Single scrape attempt using CloakBrowser (or Playwright fallback)."""
        from scraper.stealth_browser import launch_stealth_context

        all_raw: list[dict] = []
        total_on_server = 0
        actual_page_size = PAGE_SIZE
        page_num = 1
        _seen_raw: set[str] = set()
        product_name: str = ""
        got_response = asyncio.Event()

        async def _on_response(response) -> None:
            nonlocal total_on_server, actual_page_size
            if _REVIEW_PATH not in response.url or response.status != 200:
                return
            try:
                body = await response.text()
                data = json.loads(body)
                items, total = _extract_reviews_from_payload(data)
                new_items = []
                for item in items:
                    review_id = (
                        str(item.get("reviewId") or "")
                        or str(item.get("id") or "")
                        or str(item.get("reviewid") or "")
                    )
                    if review_id:
                        raw_key = f"id:{review_id}"
                    else:
                        content_list = item.get("reviewContentList") or []
                        raw_text = (
                            content_list[0].get("content", "") if content_list
                            else item.get("reviewContent") or item.get("content") or ""
                        )
                        ts = (
                            item.get("reviewTime")
                            or item.get("gmtCreateTime")
                            or item.get("createdTime")
                            or ""
                        )
                        rating = item.get("rating") or item.get("score") or 0
                        reviewer = item.get("reviewerName") or item.get("reviewer") or ""
                        raw_key = hashlib.md5(
                            f"{str(raw_text)}|{ts}|{rating}|{reviewer}".encode()
                        ).hexdigest()
                    if raw_key not in _seen_raw:
                        _seen_raw.add(raw_key)
                        new_items.append(item)
                if new_items:
                    if actual_page_size == PAGE_SIZE:
                        actual_page_size = len(new_items)
                    all_raw.extend(new_items)
                    log.info(
                        "[Lazada] +%d reviews (dedup %d, total: %d)",
                        len(new_items), len(items) - len(new_items), len(all_raw)
                    )
                    if progress_callback:
                        progress_callback(len(all_raw))
                if total > total_on_server:
                    total_on_server = total
                got_response.set()
            except Exception as exc:
                log.debug("[Lazada] Response parse error: %s", exc)

        try:
            import time
            self._t0 = time.time()
            context = await launch_stealth_context(
                storage_state=str(self._state_file) if self._state_file.exists() else None,
                headless=self.headless,
                humanize=False,
            )
            page = await context.new_page()
            page.on("response", _on_response)

            got_response.clear()
            await page.goto(product_url, wait_until="domcontentloaded", timeout=35_000)

            # Check for verification/captcha page
            page_url = page.url.lower()
            page_title = ""
            try:
                page_title = (await page.title()).lower()
            except Exception:
                pass

            is_verify_page = any(kw in page_url for kw in ["verify", "captcha", "security", "login"])
            is_verify_page = is_verify_page or any(kw in page_title for kw in ["verify", "xác minh", "security"])

            if is_verify_page and not self.headless:
                bar = "-" * 60
                print(f"\n  {bar}")
                print(f"  [Lazada] 🔒 BROWSER REQUIRES VERIFICATION")
                print(f"  {bar}")
                print(f"  Lazada requires you to verify that you are human.")
                print(f"  👉 Please complete the verification in the browser window.")
                print(f"  After completing, the product page will reload automatically.")
                print(f"  {bar}")

                # Wait up to 300s for navigation away from verify page
                for _ in range(60):  # 60 * 5s = 300s
                    await page.wait_for_timeout(5000)
                    cur_url = page.url.lower()
                    if "login" in cur_url and not any(kw in cur_url for kw in ["verify", "captcha", "security"]):
                        print("  [Lazada] 🔄 Redirected to login page. Going back to product...")
                        try:
                            await page.goto(product_url, wait_until="domcontentloaded", timeout=35000)
                        except Exception:
                            pass
                        break

                    if not any(kw in cur_url for kw in ["verify", "captcha", "security", "login"]):
                        print("  [Lazada] ✅ Verification successful! Reloading product page...")
                        await page.wait_for_timeout(2000)
                        try:
                            await page.goto(product_url, wait_until="domcontentloaded", timeout=35000)
                        except Exception:
                            pass
                        break
                else:
                    print("  [Lazada] ⚠️ Verification timeout (300s). Aborting.")
                    await context.close()
                    return [], ""

            try:
                await page.evaluate("window.scrollBy(0, document.body.scrollHeight * 0.5)")
                await page.wait_for_timeout(2000)
            except Exception:
                pass

            try:
                h1_el = page.locator('h1').first
                if await h1_el.count() > 0:
                    product_name = (await h1_el.inner_text()).strip()
                if not product_name:
                    title = await page.title()
                    product_name = title.split('|')[0].strip()
            except Exception:
                pass

            print(
                "  [Lazada] Waiting for review API...\n"
                "  -> If captcha appears, solve it manually in the browser."
            )

            def _has_real_data() -> bool:
                return len(all_raw) > 0 or total_on_server > 0

            page1_ok = False

            try:
                await asyncio.wait_for(_await_event(got_response), timeout=30.0)
                page1_ok = _has_real_data()
            except asyncio.TimeoutError:
                pass

            if not page1_ok:
                # Check for captcha popup before deep scrolling
                try:
                    has_captcha = await page.evaluate("""() => {
                        return !!document.querySelector('iframe[src*="baxia"]') || 
                               !!document.querySelector('iframe[src*="sec.lazada"]') ||
                               !!document.querySelector('#baxia-dialog-content');
                    }""")
                    if has_captcha:
                        print("  [Lazada] 🔒 Captcha popup detected! Vui lòng giải quyết captcha trong trình duyệt (tối đa 5 phút)...")
                        page1_ok = await _captcha_pause_and_resume(
                            got_response=got_response,
                            check_fn=_has_real_data,
                            context="page 1 popup",
                        )
                except Exception:
                    pass

            if not page1_ok:
                print("  [Lazada] Deep scroll to trigger review API...")
                got_response.clear()
                try:
                    await page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
                    await page.wait_for_timeout(2000)
                except Exception:
                    pass
                try:
                    await asyncio.wait_for(_await_event(got_response), timeout=15.0)
                    page1_ok = _has_real_data()
                except asyncio.TimeoutError:
                    pass

            if not page1_ok:
                print("  [Lazada] Trying to click review tab...")
                for sel in ["[data-spm='tab_ratings']", "[class*='pdp-tabs'] a"]:
                    try:
                        el = page.locator(sel).first
                        if await el.count() > 0:
                            got_response.clear()
                            await el.click(timeout=3000)
                            await page.wait_for_timeout(1500)
                            try:
                                await asyncio.wait_for(_await_event(got_response), timeout=10.0)
                                if _has_real_data():
                                    page1_ok = True
                                    break
                            except asyncio.TimeoutError:
                                pass
                    except Exception:
                        continue

            if not page1_ok:
                page1_ok = await _captcha_pause_and_resume(
                    got_response=got_response,
                    check_fn=_has_real_data,
                    context="page 1",
                )

            print(
                f"  [OK] Page 1: +{len(all_raw)} reviews"
                f" | Server total: {total_on_server:,}"
            )

            if not page1_ok:
                await context.close()
                return all_raw, product_name

            try:
                await context.storage_state(path=str(self._state_file))
            except Exception:
                pass

            await self._scroll_to_review_section(page)

            target = max_reviews if max_reviews > 0 else total_on_server
            stale_pages = 0  # pages with 0 new reviews
            MAX_STALE_PAGES = 5  # stop after N consecutive stale pages

            while (max_reviews == 0 or len(all_raw) < max_reviews) and page_num <= self.max_pages:
                if total_on_server > 0:
                    total_pages = (total_on_server + actual_page_size - 1) // actual_page_size
                    if page_num >= total_pages:
                        print(f"  [Lazada] Reached last page {total_pages}.")
                        break

                prev_count = len(all_raw)
                clicked = await self._click_next_page(page, got_response)
                if not clicked:
                    print(f"  [Lazada] No more Next button (or stopped by user).")
                    break

                page_num += 1
                new_this_page = len(all_raw) - prev_count

                # Early stop: if N consecutive pages return 0 new reviews, stop
                if new_this_page == 0:
                    stale_pages += 1
                    if stale_pages >= MAX_STALE_PAGES:
                        print(f"  [Lazada] {MAX_STALE_PAGES} pages with 0 new reviews — stopping.")
                        print(f"  [Lazada] Lazada caps reviews at ~{len(all_raw)} for this session.")
                        break
                else:
                    stale_pages = 0

                elapsed = time.time() - self._t0 if self._t0 else 0
                speed = len(all_raw) / elapsed if elapsed > 0 else 0
                remaining = max(0, target - len(all_raw))
                eta = remaining / speed if speed > 0 else 0
                eta_str = f"{eta/60:.1f}m" if eta > 60 else f"{eta:.0f}s"
                pct = len(all_raw) / target * 100 if target > 0 else 0
                # Only print every 5 pages to reduce noise (or always for pages with data)
                if new_this_page > 0 or page_num % 5 == 0:
                    print(
                        f"  [OK] Page {page_num}: {len(all_raw):,}/{target:,} ({pct:.1f}%)"
                        f" | {speed:.1f} rev/s | ETA {eta_str}"
                    )
                await page.wait_for_timeout(int(self.delay * 1000))

            await context.close()

        except Exception as exc:
            log.error("[Lazada] Error: %s", exc, exc_info=True)
            print(f"  [Lazada] Error: {exc}")

        return all_raw, product_name

    # ------------------------------------------------------------------
    # UI helpers
    # ------------------------------------------------------------------

    async def _scroll_to_review_section(self, page) -> None:
        """Scroll to the review section so pagination appears."""
        for sel in _REVIEW_SECTION_SELECTORS:
            try:
                el = page.locator(sel).first
                if await el.count() > 0:
                    await el.scroll_into_view_if_needed(timeout=3000)
                    await page.wait_for_timeout(300)
                    return
            except Exception:
                continue
        # Fallback: scroll to end of page
        try:
            await page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
            await page.wait_for_timeout(300)
        except Exception:
            pass

    async def _click_next_page(self, page, got_response: asyncio.Event) -> bool:
        """
        Click 'Next Page' button using JavaScript (primary) to avoid
        scroll/viewport issues when pagination changes format (e.g., < 1 ... 5 6 7 ... 8 >).
        Playwright CSS click as fallback.
        If no response is received within 10s (possibly due to CAPTCHA),
        wait up to CAPTCHA_AUTO_WAIT seconds for the user to solve it manually.
        Return True if click is successful AND a new review response is received.
        """
        clicked = await self._do_click_next(page, got_response)
        if not clicked:
            is_blocked = False
            try:
                if "verify" in page.url or "login" in page.url:
                    is_blocked = True
                elif await page.locator("iframe[src*='baxia']").count() > 0 or await page.locator("iframe[src*='captcha']").count() > 0:
                    is_blocked = True
            except Exception:
                pass
                
            if is_blocked:
                print("  [Lazada] 🔒 Captcha popup detected while clicking Next!")
                await _captcha_pause_and_resume(got_response, lambda: True, context="mid-scrape-click")
                await page.wait_for_timeout(2000)
                clicked = await self._do_click_next(page, got_response)
                if not clicked:
                    return False
            else:
                return False

        got = await self._wait_for_response_or_captcha(page, got_response)
        return got

    async def _do_click_next(self, page, got_response: asyncio.Event) -> bool:
        """
        Execute Next button click (JS primary -> Playwright fallback).
        Return True if found and clicked, regardless of whether a response is received.
        """
        # Primary: JavaScript click (bypass scroll & viewport)
        try:
            got_response.clear()
            was_clicked: bool = await page.evaluate("""
                () => {
                    // Lazada uses iweb-pagination-*
                    const candidates = [
                        'li.iweb-pagination-next:not(.iweb-pagination-disabled) button',
                        'li.iweb-pagination-next:not(.iweb-pagination-disabled)',
                        'button.iweb-pagination-item-link[aria-label="next page"]',
                        'button.iweb-pagination-item-link[aria-label*="next"]',
                    ];
                    for (const sel of candidates) {
                        const el = document.querySelector(sel);
                        if (el && !el.disabled && !el.closest('.iweb-pagination-disabled')) {
                            el.scrollIntoView({ block: 'center', behavior: 'instant' });
                            el.click();
                            return true;
                        }
                    }
                    return false;
                }
            """)
            if was_clicked:
                return True
        except Exception as exc:
            log.debug("[Lazada] JS click failed: %s", exc)

        # Fallback: Playwright locator click
        await self._scroll_to_review_section(page)
        for sel in _NEXT_PAGE_SELECTORS:
            try:
                btn = page.locator(sel).first
                if await btn.count() == 0:
                    continue
                if not await btn.is_enabled():
                    continue
                await btn.scroll_into_view_if_needed(timeout=2000)
                got_response.clear()
                await btn.click(force=True, timeout=4000)
                return True
            except Exception as exc:
                log.debug("[Lazada] Selector '%s' failed: %s", sel, exc)
                continue

        return False

    async def _wait_for_response_or_captcha(
        self, page, got_response: asyncio.Event
    ) -> bool:
        """
        Wait for review API response after clicking Next.
        - If received within 5s -> return True immediately.
        - If not -> wait up to CAPTCHA_AUTO_WAIT for user to manually solve CAPTCHA in browser.
        """
        # Normal wait 5s
        try:
            await asyncio.wait_for(_await_event(got_response), timeout=5.0)
            return True
        except asyncio.TimeoutError:
            pass

        # After 5s without response -> suspected captcha -> wait automatically
        return await _captcha_pause_and_resume(
            got_response=got_response,
            check_fn=lambda: True,
            context="pagination",
        )


# ---------------------------------------------------------------------------
# Utility
# ---------------------------------------------------------------------------


async def _await_event(event: asyncio.Event) -> None:
    """Wait for asyncio.Event to be set (light polling 50ms)."""
    while not event.is_set():
        await asyncio.sleep(0.05)
    event.clear()


async def _captcha_pause_and_resume(
    got_response: asyncio.Event,
    check_fn,
    context: str = "pagination",
) -> bool:
    """
    Pause & resume mechanism when encountering CAPTCHA / bot-check:

    1. Automatically wait CAPTCHA_AUTO_WAIT seconds (polling CAPTCHA_POLL_CHUNK at a time).
       -> if response arrives naturally, continue immediately.
    2. If timeout expires, abort the scrape and return what we have so far.
    Returns True if data is eventually received, False if timed out.
    """
    bar = "-" * 60
    # Wait automatically
    print(f"\n  {bar}")
    print(f"  [Lazada] 🔒 BOT CHECK BLOCKED ({context})")
    print(f"  {bar}")
    print("  Lazada has activated a captcha / bot-check.")
    print("  👉 Please solve the captcha in the open browser window.")
    print(f"  Will wait up to {int(CAPTCHA_AUTO_WAIT)} seconds for you to solve it...")
    print(f"  {bar}")

    deadline = CAPTCHA_AUTO_WAIT
    while deadline > 0:
        got_response.clear()
        chunk = min(CAPTCHA_POLL_CHUNK, deadline)
        try:
            await asyncio.wait_for(_await_event(got_response), timeout=chunk)
            if check_fn():
                print("  [Lazada] ✅ Automatically received response - continuing.")
                return True
        except asyncio.TimeoutError:
            pass
        deadline -= chunk
        if deadline > 0:
            print(f"  [Lazada] ⏳ Waiting for you to solve CAPTCHA... {int(deadline)}s remaining")

    print(f"\n  [Lazada] ⚠️ Timeout reached after {int(CAPTCHA_AUTO_WAIT)}s. Stopping and saving data.")
    return False
